package common;

public enum EasternKingdomZone
{
	ALTERAC_MOUNTAINS
	, ARATHI_HIGHLANDS
	, BADLANDS
	, BLASTED_LANDS
	, BURNING_STEPPES
	, DEADWIND_PASS
	, DUN_MOROGH
	, DUSKWOOD
	, EASTERN_PLAGUELANDS
	, ELWYNN_FOREST
	, HILLSBRAD_FOOTHILLS
	, LOCH_MODAN
	, REDRIDGE_MOUNTAINS
	, SEARING_GORGE
	, SILVERPINE_FOREST
	, STRANGLETHORN_VALE
	, SWAMP_OF_SORROWS
	, THE_HINTERLANDS
	, TIRISFAL_GLADES
	, WESTERN_PLAGUELANDS
	, WESTFALL
	, WETLANDS
}